In [1]:
import cv2
import numpy as np
from PIL import Image

In [16]:
class Shift(object):
    def __init__(self, shift):
        self.shift = shift

    def __call__(self, img):
        im = np.array(img, dtype= np.float)
        rows, cols, chan = im.shape
        shifted_img = cv2.warpAffine(im, self.shift, (cols, rows))
        shifted_img = shifted_img.reshape((cols, rows, chan))

        return shifted_img

In [40]:
class MaxNormalization(object):
    def __init__(self, max_val):
        self.max = max_val

    def __call__(self, img):
        norm_img = np.array(img, dtype= np.float) * self.max
        rows, cols = norm_img.shape
        norm_img = norm_img.reshape((cols, rows, 1))

        print(norm_img.shape)

        return norm_img
    
class BiasNoise(object):
    def __init__(self, bias_noise):
        self.bias_noise = bias_noise

    def __call__(self, img):
        noisy_img = np.array(img, dtype= np.float) + self.bias_noise
        rows, cols, chan = noisy_img.shape
        noisy_img = noisy_img.reshape((cols, rows, chan))
        noisy_img_clipped = np.clip(noisy_img, 0, 255)  # we might get out of bounds due to noise

        return noisy_img_clipped

'''
Adds Gaussian Noise to the image with mean and std.
The bias is added when the object is called
'''
class GaussianNoise(object):
    def __init__(self, std, mean=0):
        self.mean = mean
        self.std = std

    def __call__(self, img):
        noisy_img = np.array(img, dtype= np.float)
        rows, cols, chan = noisy_img.shape
        noisy_img = noisy_img + np.random.normal(self.mean, self.std, noisy_img.shape)
        noisy_img = noisy_img.reshape((cols, rows, chan))
        noisy_img_clipped = np.clip(noisy_img, 0, 255)  # we might get out of bounds due to noise

        return noisy_img_clipped

In [41]:
shift = -150
translate = Shift(np.float32([[1, 0, shift], [0, 1, 0]]))
g = GaussianNoise(5)
b = BiasNoise(10)
maxnorm = MaxNormalization(0.0038910505836575876)

In [42]:
img = './5400.png'
image = Image.open(img)


In [43]:
im = maxnorm(image)
im = translate(im)
print(im)

(640, 480, 1)
[[[138.15953307]
  [138.19844358]
  [124.38910506]
  ...
  [130.85214008]
  [101.6848249 ]
  [139.24513619]]

 [[139.61867704]
  [137.61478599]
  [123.90272374]
  ...
  [130.47081712]
  [134.0233463 ]
  [170.62256809]]

 [[154.11673152]
  [142.9688716 ]
  [145.38910506]
  ...
  [  0.        ]
  [  0.        ]
  [  0.        ]]

 ...

 [[171.04280156]
  [150.42412451]
  [130.23735409]
  ...
  [173.76653696]
  [144.83268482]
  [164.09727626]]

 [[151.85603113]
  [127.0311284 ]
  [128.692607  ]
  ...
  [153.44747082]
  [112.17120623]
  [146.46692607]]

 [[138.70817121]
  [135.96108949]
  [140.72373541]
  ...
  [  0.        ]
  [  0.        ]
  [  0.        ]]]


In [45]:
img = './5400.png'
image = Image.open(img)
im = maxnorm(image)
g(im)

(640, 480, 1)


array([[[157.46663218],
        [155.94276928],
        [166.74501532],
        ...,
        [164.27545381],
        [161.83294662],
        [168.21036099]],

       [[160.14672928],
        [160.49620672],
        [166.23569918],
        ...,
        [155.32412835],
        [154.5912619 ],
        [155.56210249]],

       [[158.09564969],
        [170.0389225 ],
        [155.39384351],
        ...,
        [155.51934933],
        [160.08434042],
        [157.80905928]],

       ...,

       [[180.57838255],
        [176.05996407],
        [172.94351006],
        ...,
        [173.09817473],
        [167.67972936],
        [162.89573038]],

       [[159.19704296],
        [157.19666792],
        [154.50124539],
        ...,
        [164.57075733],
        [163.46306706],
        [167.74300361]],

       [[155.82224296],
        [154.33035997],
        [147.00668032],
        ...,
        [162.34236478],
        [169.92794827],
        [166.06341945]]])

In [47]:
img = './5400.png'
image = Image.open(img)
im = maxnorm(image)
b(im)

(640, 480, 1)


array([[[167.43579767],
        [167.43579767],
        [167.43579767],
        ...,
        [175.17898833],
        [175.17898833],
        [175.17898833]],

       [[172.35797665],
        [172.35797665],
        [172.35797665],
        ...,
        [164.66536965],
        [164.66536965],
        [164.66536965]],

       [[168.65758755],
        [168.65758755],
        [168.65758755],
        ...,
        [168.84046693],
        [168.84046693],
        [168.84046693]],

       ...,

       [[179.9688716 ],
        [179.9688716 ],
        [179.9688716 ],
        ...,
        [177.22957198],
        [177.22957198],
        [177.22957198]],

       [[165.0155642 ],
        [165.0155642 ],
        [165.0155642 ],
        ...,
        [176.82101167],
        [176.82101167],
        [176.82101167]],

       [[161.28404669],
        [161.28404669],
        [161.28404669],
        ...,
        [172.03501946],
        [172.03501946],
        [172.03501946]]])