In [28]:
import numpy as np
import cv2
import torch
from torchvision import transforms
from PIL import Image
import LenslessDataset
from normalize import *
from torch.utils.data import ConcatDataset
import os

In [29]:
root_dir = '/Volumes/MyPassport/ML/Deep_Learning/lensless_image_data/'
train_csv = '/Users/brianrodriguez/Development/LenlessCameraML/data_csv/kfold_train_copy.csv'
test_csv = '/Users/brianrodriguez/Development/LenlessCameraML/data_csv/kfold_test_copy.csv'

csv_data = pd.read_csv(train_csv)
img_name = os.path.join(root_dir, csv_data.iloc[0, 0])

In [47]:
# image = Image.open(img_name)
# label = csv_data.iloc[idx, 1]
# d = transforms.Compose([transforms.Resize((28, 28)),
#         MaxNormalization(0.0038910505836575876),
#         transforms.ToTensor()])
shift = 50
s = np.random.randint(-shift, shift+1)
s

29

In [48]:
data_transforms = [transforms.Compose([transforms.Resize((28, 28)),
        MaxNormalization(0.0038910505836575876),
        transforms.ToTensor()]),
        transforms.Compose([transforms.Resize((28, 28)),
        MaxNormalization(0.0038910505836575876),
        CastTensor(''),
        transforms.Normalize([157.11056947927852], [139.749640327443])])]
        
rigor = True

train_datasets = []
test_datasets = []

for idx, data_transform in enumerate(data_transforms):
    train_datasets.append(LenslessDataset.LenslessDataset(
    csv_file= train_csv,
    root_dir= root_dir,
    transform= data_transform
    ))
    test_datasets.append(LenslessDataset.LenslessDataset(
    csv_file= test_csv,
    root_dir= root_dir,
    transform= data_transform
    ))
   
train_loader = torch.utils.data.DataLoader(
ConcatDataset(train_datasets),
batch_size= 8,
shuffle= True,
)

test_loader = torch.utils.data.DataLoader(
ConcatDataset(test_datasets),
batch_size= 8,
shuffle= True,
)

In [41]:
for idx, (inputs, targets) in enumerate(train_loader):
    print(inputs)

tensor([[[[  0.7289,   0.7013,   0.6897,  ...,   0.6780,   0.6896,   0.6930],
          [  0.7548,   0.7293,   0.7104,  ...,   0.6956,   0.7089,   0.7126],
          [  0.7373,   0.7094,   0.6864,  ...,   0.6775,   0.6910,   0.6856],
          ...,
          [  0.7485,   0.7246,   0.7081,  ...,   0.7002,   0.7078,   0.7008],
          [  0.7741,   0.7502,   0.7329,  ...,   0.7178,   0.7243,   0.7220],
          [  0.7411,   0.7178,   0.7120,  ...,   0.7001,   0.7039,   0.7007]]],


        [[[  0.7023,   0.6755,   0.6649,  ...,   0.6713,   0.6844,   0.6777],
          [  0.7293,   0.7046,   0.6880,  ...,   0.6879,   0.7014,   0.6946],
          [  0.7115,   0.6833,   0.6645,  ...,   0.6714,   0.6836,   0.6740],
          ...,
          [  0.7272,   0.6996,   0.6870,  ...,   0.6954,   0.7003,   0.6891],
          [  0.7489,   0.7242,   0.7105,  ...,   0.7097,   0.7146,   0.7063],
          [  0.7127,   0.6903,   0.6858,  ...,   0.6910,   0.6945,   0.6840]]],


        [[[171.8016, 165.5

tensor([[[[  0.6481,   0.6195,   0.6101,  ...,   0.6454,   0.6533,   0.6455],
          [  0.6740,   0.6476,   0.6329,  ...,   0.6621,   0.6727,   0.6673],
          [  0.6555,   0.6293,   0.6131,  ...,   0.6445,   0.6567,   0.6479],
          ...,
          [  0.6722,   0.6482,   0.6391,  ...,   0.6688,   0.6711,   0.6607],
          [  0.6947,   0.6725,   0.6602,  ...,   0.6802,   0.6862,   0.6772],
          [  0.6610,   0.6407,   0.6390,  ...,   0.6624,   0.6652,   0.6574]]],


        [[[  0.7433,   0.7196,   0.7108,  ...,   0.7189,   0.7293,   0.7235],
          [  0.7645,   0.7422,   0.7278,  ...,   0.7342,   0.7440,   0.7369],
          [  0.7488,   0.7274,   0.7098,  ...,   0.7206,   0.7316,   0.7205],
          ...,
          [  0.7612,   0.7403,   0.7281,  ...,   0.7395,   0.7422,   0.7339],
          [  0.7809,   0.7605,   0.7494,  ...,   0.7514,   0.7552,   0.7484],
          [  0.7525,   0.7318,   0.7282,  ...,   0.7373,   0.7383,   0.7288]]],


        [[[  0.6882,   0.6

tensor([[[[  0.7024,   0.6763,   0.6654,  ...,   0.6843,   0.6948,   0.6851],
          [  0.7260,   0.7028,   0.6879,  ...,   0.7001,   0.7105,   0.7012],
          [  0.7122,   0.6863,   0.6703,  ...,   0.6838,   0.6942,   0.6827],
          ...,
          [  0.7261,   0.7008,   0.6899,  ...,   0.7050,   0.7087,   0.6978],
          [  0.7454,   0.7236,   0.7120,  ...,   0.7170,   0.7228,   0.7146],
          [  0.7113,   0.6902,   0.6890,  ...,   0.7022,   0.7061,   0.6933]]],


        [[[175.4980, 168.1984, 165.5876,  ..., 168.7237, 171.6654, 169.4436],
          [182.6615, 175.1051, 171.1284,  ..., 174.2490, 176.6498, 174.2140],
          [177.5097, 170.4086, 165.2957,  ..., 169.4047, 171.9922, 168.2374],
          ...,
          [181.0311, 174.3619, 171.3191,  ..., 175.6031, 175.7198, 171.7004],
          [187.0078, 181.7549, 178.1751,  ..., 178.2957, 179.2685, 176.7938],
          [178.5914, 172.9183, 172.2062,  ..., 174.1051, 174.4086, 170.4942]]],


        [[[189.5486, 183.4